name: HFAPatchIPA

options:
  bundleIdPrefix: com.hfa
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "16.0"

packages:
  Zip:
    url: https://github.com/marmelroy/Zip.git
    from: 2.1.2
  Zsign:
    path: Vendor/Zsign

targets:
  HFAPatchIPA:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Resources
        buildPhase: resources
    dependencies:
      - package: Zip
        product: Zip
      - package: Zsign
        product: Zsign
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: HFAPatchIPA
        LSApplicationCategoryType: public.app-category.developer-tools
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hfa.patchipa
        PRODUCT_NAME: HFAPatchIPA
        MARKETING_VERSION: 1.0.1
        CURRENT_PROJECT_VERSION: 2
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: NO
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
    scheme:
      testTargets: []
