#!/usr/bin/env python3
from pathlib import Path
import sys
root = Path(sys.argv[1] if len(sys.argv)>1 else 'upstream')
p = root/'addonProfilerLite.cpp'
s = p.read_text(encoding='utf-8')

def once(old,new,label):
    global s
    n=s.count(old)
    if n!=1:
        raise SystemExit(f'{label}: expected 1, got {n}')
    s=s.replace(old,new,1)

once('''struct LongFrame {\n    std::string time;\n    double frameMs = 0.0;\n    double measuredLuaMs = 0.0;\n    std::string addon;\n    std::string file;\n    double associatedAddonMs = 0.0;\n    double associatedAddonPct = 0.0;\n    double measuredLuaPct = 0.0;\n    double unmeasuredMs = 0.0;\n    int contributionLevel = 0;\n    std::string contributionLabel;\n};\n''', '''struct LongFrameContributor {\n    std::string addon;\n    std::string file;\n    double ms = 0.0;\n    double pct = 0.0;\n    int contributionLevel = 0;\n    std::string contributionLabel;\n};\n\nstruct LongFrame {\n    std::string time;\n    double frameMs = 0.0;\n    double measuredLuaMs = 0.0;\n    std::string addon;\n    std::string file;\n    double associatedAddonMs = 0.0;\n    double associatedAddonPct = 0.0;\n    double measuredLuaPct = 0.0;\n    double unmeasuredMs = 0.0;\n    int contributionLevel = 0;\n    std::string contributionLabel;\n    std::vector<LongFrameContributor> contributors;\n};\n''','long frame contributor struct')

once('''        pushBoolField(L,"effectiveContribution",it->contributionLevel >= 1);\n        pushNumberField(L,"unmeasuredMs",it->unmeasuredMs);\n        lua_settable(L,-3);\n''', '''        pushBoolField(L,"effectiveContribution",it->contributionLevel >= 1);\n        pushNumberField(L,"unmeasuredMs",it->unmeasuredMs);\n        pushNumberField(L,"contributorCount",(double)it->contributors.size());\n        lua_pushstring(L,"contributors");\n        lua_newtable(L);\n        int ci = 1;\n        for (const auto& c : it->contributors) {\n            lua_pushnumber(L,ci++);\n            lua_newtable(L);\n            pushStringField(L,"addon",c.addon);\n            pushStringField(L,"file",c.file);\n            pushNumberField(L,"ms",c.ms);\n            pushNumberField(L,"pct",c.pct);\n            pushNumberField(L,"contributionLevel",(double)c.contributionLevel);\n            pushStringField(L,"contributionLabel",c.contributionLabel);\n            pushBoolField(L,"effectiveContribution",c.contributionLevel >= 1);\n            lua_settable(L,-3);\n        }\n        lua_settable(L,-3);\n        lua_settable(L,-3);\n''','push contributor table')

once('''        LongFrame lf; lf.time=clockText();lf.frameMs=frameMs;lf.measuredLuaMs=measuredLuaMs;lf.addon=topAddon.empty()?"未归属/非监控Lua":topAddon;lf.file=topFile;\n        lf.associatedAddonMs=associatedAddonMs;\n        lf.associatedAddonPct=frameMs>0.0?associatedAddonMs*100.0/frameMs:0.0;\n        lf.measuredLuaPct=frameMs>0.0?measuredLuaMs*100.0/frameMs:0.0;\n        lf.unmeasuredMs=frameMs>measuredLuaMs?frameMs-measuredLuaMs:0.0;\n        lf.contributionLevel=contributionLevel;\n        lf.contributionLabel=longFrameContributionLabel(contributionLevel);\n        gLongFrames.push_back(std::move(lf)); while(gLongFrames.size()>kMaxLongFrames)gLongFrames.pop_front();\n''', '''        LongFrame lf; lf.time=clockText();lf.frameMs=frameMs;lf.measuredLuaMs=measuredLuaMs;lf.addon=topAddon.empty()?"未归属/非监控Lua":topAddon;lf.file=topFile;\n        lf.associatedAddonMs=associatedAddonMs;\n        lf.associatedAddonPct=frameMs>0.0?associatedAddonMs*100.0/frameMs:0.0;\n        lf.measuredLuaPct=frameMs>0.0?measuredLuaMs*100.0/frameMs:0.0;\n        lf.unmeasuredMs=frameMs>measuredLuaMs?frameMs-measuredLuaMs:0.0;\n        lf.contributionLevel=contributionLevel;\n        lf.contributionLabel=longFrameContributionLabel(contributionLevel);\n\n        // Snapshot top measured addons on this exact long frame before currentFrameTicks are cleared.\n        // This extra sort runs only on long frames, not on normal frames.\n        std::vector<std::pair<std::size_t,std::uint64_t>> ranked;\n        ranked.reserve(gAddons.size());\n        for (std::size_t ai=0; ai<gAddons.size(); ++ai) {\n            if (gAddons[ai].s.currentFrameTicks) ranked.push_back({ai,gAddons[ai].s.currentFrameTicks});\n        }\n        std::sort(ranked.begin(), ranked.end(), [](const auto& x, const auto& y){ return x.second > y.second; });\n        const std::size_t keep = std::min<std::size_t>(5, ranked.size());\n        lf.contributors.reserve(keep);\n        for (std::size_t ri=0; ri<keep; ++ri) {\n            const std::size_t ai = ranked[ri].first;\n            const std::uint64_t at = ranked[ri].second;\n            LongFrameContributor c;\n            c.addon = gAddons[ai].name;\n            c.ms = ticksMs(at);\n            c.pct = frameMs>0.0 ? c.ms*100.0/frameMs : 0.0;\n            c.contributionLevel = longFrameContributionLevel(frameMs,c.ms);\n            c.contributionLabel = longFrameContributionLabel(c.contributionLevel);\n            std::uint64_t bestFileTicks = 0;\n            for (const auto& fs : gFiles) {\n                if (fs.addon==c.addon && fs.s.currentFrameTicks>bestFileTicks) {\n                    bestFileTicks=fs.s.currentFrameTicks;\n                    c.file=fs.file;\n                }\n            }\n            lf.contributors.push_back(std::move(c));\n        }\n\n        gLongFrames.push_back(std::move(lf)); while(gLongFrames.size()>kMaxLongFrames)gLongFrames.pop_front();\n''','capture top 5 contributors')

once('''    pushNumberField(L, "longFrameThresholdMs", gLongFrameMs);\n    pushNumberField(L, "longFrameContributionMinMs", 2.0);\n''','''    pushNumberField(L, "longFrameThresholdMs", gLongFrameMs);\n    pushNumberField(L, "longFrameContributorLimit", 5.0);\n    pushNumberField(L, "longFrameRecordVersion", 2.0);\n    pushNumberField(L, "longFrameContributionMinMs", 2.0);\n''','snapshot record metadata')

once('''static constexpr const char* kB1R5R5Isolation = "B1R5R5_DEEP_LIGHT_ISOLATION";\n''','''static constexpr const char* kB1R5R5Isolation = "B1R5R5_DEEP_LIGHT_ISOLATION";\nstatic constexpr const char* kB1R5R8LongFrameDetails = "B1R5R8_LONGFRAME_TOP5_DETAILS";\n''','version marker')
once('''    pushStringField(L, "version", kVersion);\n''','''    pushStringField(L, "version", kVersion);\n    pushStringField(L, "longFrameDetailsBuild", kB1R5R8LongFrameDetails);\n''','expose marker')

p.write_text(s,encoding='utf-8')
print('B1R5R8 long-frame details patch OK')
