#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <objc/runtime.h>
#include <math.h>
#import "ZNFeatureControlModel.h"
#import "ZNFeatureMetadataCodec.h"
#import "ZNRangeControl.h"
#import "ZNStaticDispatchRuntime.h"
#import "ZNStaticPatchFormat.h"
#import "ZNTheme.h"
#import "ZNValueTypeModel.h"
#import "ZNPatchCore.h"

static const NSInteger kZN65ToggleTagBase=450000,kZN65NumberTagBase=469000,kZN65ActionTagBase=470000,kZN65SliderTagBase=471000,kZN65NumberExecuteTagBase=472000;
@interface ZNStaticPatchRecord (ZNFeatureRuntimeControlEntry) @property(nonatomic,assign) ZN44StaticEntry *entry; @end
@interface ZNRuntimeMenuControllerV040 : NSObject
@property(nonatomic,strong) UIView *contentView; @property(nonatomic,strong) UIWindow *hostWindow; @property(nonatomic,strong) ZNTheme *theme;
- (UIButton *)zn40_button:(NSString *)title selector:(SEL)selector frame:(CGRect)frame;
- (void)zn50_renderFeatureGroupsFull; - (void)zn50_renderFeatureGroupsCompact;
@end
static NSString *ZN65Trim(NSString *v){return [v?:@"" stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];}
static NSDictionary *ZN65DisplayMetadata(ZNStaticPatchRecord *r){NSDictionary *e=r.entry?ZNFeatureMetadataDecodeEntry(r.entry):nil;if(e)return e;NSString *title=ZN65Trim(r.title),*group=ZN65Trim(r.group);if(!title.length||[title hasPrefix:@"Patch #"])title=[NSString stringWithFormat:@"功能 #%u",r.patchID];if(!group.length)group=@"Imported";return @{@"featureID":@0,@"title":title,@"group":group,@"explicitGroup":@([group caseInsensitiveCompare:@"Imported"]!=NSOrderedSame),@"controlType":@(ZNFeatureControlTypeSwitch),@"valueType":@(ZNValueTypeAuto)};}
static NSArray *ZN65FeatureGroups(void){ZNStaticDispatchRuntime *rt=[ZNStaticDispatchRuntime sharedRuntime];[rt refresh];NSMutableArray *order=[NSMutableArray array];NSMutableDictionary *members=[NSMutableDictionary dictionary],*metadata=[NSMutableDictionary dictionary];for(ZNStaticPatchRecord *r in rt.records){NSDictionary *d=ZN65DisplayMetadata(r);NSString *group=ZN65Trim(d[@"group"]),*title=ZN65Trim(d[@"title"]);uint64_t fid=[d[@"featureID"] unsignedLongLongValue];BOOL explicitFeature=[d[@"explicitGroup"] boolValue]||(group.length&&[group caseInsensitiveCompare:@"Imported"]!=NSOrderedSame);NSString *key=fid?[NSString stringWithFormat:@"id:%016llx",fid]:(explicitFeature?[@"group:" stringByAppendingString:group.lowercaseString]:[NSString stringWithFormat:@"patch:%@:%u",r.target.lowercaseString?:@"",r.patchID]);if(!members[key]){members[key]=[NSMutableArray array];ZNFeatureControlType ct=r.entry?ZNFeatureControlTypeFromFlags(r.entry->flags):ZNFeatureControlTypeSwitch;ZNValueType vt=r.entry?ZNFeatureValueTypeFromFlags(r.entry->flags):ZNValueTypeAuto;metadata[key]=[@{@"key":key,@"featureID":@(fid),@"title":explicitFeature&&group.length?group:(title.length?title:@"功能"),@"controlType":@(ct),@"valueType":@(vt)} mutableCopy];[order addObject:key];}[members[key] addObject:r];}NSMutableArray *out=[NSMutableArray array];for(NSString *key in order){NSMutableDictionary *item=[metadata[key] mutableCopy];item[@"records"]=[members[key] copy];[out addObject:[item copy]];}return out;}
static NSString *ZN65PreferenceKey(NSDictionary *f,NSString *s){uint64_t fid=[f[@"featureID"] unsignedLongLongValue];NSString *idn=fid?[NSString stringWithFormat:@"%016llx",fid]:[f[@"key"] description];return [NSString stringWithFormat:@"zn.fc.%@.%@",idn?:@"feature",s?:@"value"];}
static double ZN65StoredValue(NSDictionary *f,double fallback){id v=[NSUserDefaults.standardUserDefaults objectForKey:ZN65PreferenceKey(f,@"value")];return [v isKindOfClass:NSNumber.class]?[v doubleValue]:fallback;}
static NSString *ZN65StoredText(NSDictionary *f,NSString *fallback){id v=[NSUserDefaults.standardUserDefaults objectForKey:ZN65PreferenceKey(f,@"valueText")];return [v isKindOfClass:NSString.class]&&[(NSString*)v length]?(NSString*)v:(fallback?:@"1");}
static NSDictionary *ZN65EventInfo(NSDictionary *f,NSNumber *value,NSString *text){NSMutableDictionary *i=[@{@"featureID":f[@"featureID"]?:@0,@"title":f[@"title"]?:@"功能",@"controlType":f[@"controlType"]?:@(ZNFeatureControlTypeSwitch),@"valueType":f[@"valueType"]?:@(ZNValueTypeAuto),@"key":f[@"key"]?:@""} mutableCopy];if(value)i[@"value"]=value;if(text.length)i[@"valueText"]=text;return i;}
static void ZN65StoreNumberText(NSDictionary *f,NSString *text){NSString *t=ZN65Trim(text);if(!t.length)t=@"0";[NSUserDefaults.standardUserDefaults setObject:t forKey:ZN65PreferenceKey(f,@"valueText")];NSDecimalNumber *n=[NSDecimalNumber decimalNumberWithString:t locale:@{NSLocaleDecimalSeparator:@"."}];if(![n isEqualToNumber:NSDecimalNumber.notANumber])[NSUserDefaults.standardUserDefaults setDouble:n.doubleValue forKey:ZN65PreferenceKey(f,@"value")];}
@interface ZNRuntimeMenuControllerV040 (ZNFeatureRuntimeControlsV2)
- (void)zn65fc_renderFull; - (void)zn65fc_renderCompact; - (void)zn65fc_numberChanged:(UITextField*)field; - (void)zn65fc_numberReturn:(UITextField*)field; - (void)zn65fc_numberExecute:(UIButton*)button; - (void)zn65fc_actionTapped:(UIButton*)button; - (void)zn65fc_sliderCommitted:(ZNRangeControl*)slider;
@end
@implementation ZNRuntimeMenuControllerV040 (ZNFeatureRuntimeControlsV2)
- (void)zn65fc_decorateCompact:(BOOL)compact{NSArray *features=ZN65FeatureGroups();for(NSUInteger i=0;i<features.count;i++){NSDictionary *f=features[i];ZNFeatureControlType type=(ZNFeatureControlType)[f[@"controlType"] unsignedIntValue];if(type==ZNFeatureControlTypeSwitch)continue;UIView *old=[self.contentView viewWithTag:kZN65ToggleTagBase+(NSInteger)i],*card=old.superview;if(!old||!card)continue;CGRect oldFrame=old.frame;[old removeFromSuperview];ZNValueType vt=(ZNValueType)[f[@"valueType"] integerValue];if(type==ZNFeatureControlTypeNumber){CGFloat ew=compact?46:52,gap=4,tw=compact?118:136,x=CGRectGetWidth(card.bounds)-tw-(compact?7:10);UITextField *field=[[UITextField alloc]initWithFrame:CGRectMake(x,oldFrame.origin.y,tw-ew-gap,oldFrame.size.height)];field.tag=kZN65NumberTagBase+(NSInteger)i;double stored=ZN65StoredValue(f,1);NSString *fallback=ZNValueTypeIsInteger(vt)||vt==ZNValueTypeAuto?[NSString stringWithFormat:@"%.0f",stored]:[NSString stringWithFormat:@"%.6g",stored];field.text=ZN65StoredText(f,fallback);field.textAlignment=NSTextAlignmentCenter;field.keyboardType=UIKeyboardTypeNumbersAndPunctuation;field.returnKeyType=UIReturnKeyDone;field.textColor=self.theme.primaryTextColor;field.backgroundColor=[self.theme.controlColor colorWithAlphaComponent:.82];field.font=[UIFont systemFontOfSize:(compact?9:9.6) weight:UIFontWeightSemibold];field.layer.cornerRadius=7;field.layer.borderWidth=1;field.layer.borderColor=self.theme.borderColor.CGColor;[field addTarget:self action:@selector(zn65fc_numberChanged:) forControlEvents:UIControlEventEditingChanged|UIControlEventEditingDidEnd];[field addTarget:self action:@selector(zn65fc_numberReturn:) forControlEvents:UIControlEventEditingDidEndOnExit];[card addSubview:field];UIButton *execute=[self zn40_button:@"执行" selector:@selector(zn65fc_numberExecute:) frame:CGRectMake(CGRectGetMaxX(field.frame)+gap,oldFrame.origin.y,ew,oldFrame.size.height)];execute.tag=kZN65NumberExecuteTagBase+(NSInteger)i;[card addSubview:execute];}else if(type==ZNFeatureControlTypeButton){UIButton *b=[self zn40_button:@"执行" selector:@selector(zn65fc_actionTapped:) frame:oldFrame];b.tag=kZN65ActionTagBase+(NSInteger)i;[card addSubview:b];}else if(type==ZNFeatureControlTypeSlider){CGFloat w=compact?88:112;ZNRangeControl *s=[[ZNRangeControl alloc]initWithFrame:CGRectMake(CGRectGetWidth(card.bounds)-w-(compact?7:10),oldFrame.origin.y,w,oldFrame.size.height)];s.tag=kZN65SliderTagBase+(NSInteger)i;s.minimumValue=1;s.maximumValue=10;s.value=MIN(10.0,MAX(1.0,round(ZN65StoredValue(f,1))));s.minimumTrackTintColor=self.theme.accentColor;s.maximumTrackTintColor=[self.theme.trackColor colorWithAlphaComponent:.75];s.thumbTintColor=self.theme.primaryTextColor;[s addTarget:self action:@selector(zn65fc_sliderCommitted:) forControlEvents:UIControlEventPrimaryActionTriggered];[card addSubview:s];}}}
- (void)zn65fc_renderFull{[self zn65fc_renderFull];[self zn65fc_decorateCompact:NO];}
- (void)zn65fc_renderCompact{[self zn65fc_renderCompact];[self zn65fc_decorateCompact:YES];}
- (void)zn65fc_numberChanged:(UITextField*)field{NSInteger idx=field.tag-kZN65NumberTagBase;NSArray *fs=ZN65FeatureGroups();if(idx<0||(NSUInteger)idx>=fs.count)return;ZN65StoreNumberText(fs[(NSUInteger)idx],field.text);}
- (void)zn65fc_numberReturn:(UITextField*)field{[self zn65fc_numberChanged:field];[field resignFirstResponder];}
- (void)zn65fc_numberExecute:(UIButton*)button{NSInteger idx=button.tag-kZN65NumberExecuteTagBase;NSArray *fs=ZN65FeatureGroups();if(idx<0||(NSUInteger)idx>=fs.count)return;NSDictionary *f=fs[(NSUInteger)idx];NSString *text=ZN65StoredText(f,@"0");[NSNotificationCenter.defaultCenter postNotificationName:ZNFeatureNumberValueDidChangeNotification object:self userInfo:ZN65EventInfo(f,@(text.doubleValue),text)];}
- (void)zn65fc_actionTapped:(UIButton*)button{NSInteger idx=button.tag-kZN65ActionTagBase;NSArray *fs=ZN65FeatureGroups();if(idx<0||(NSUInteger)idx>=fs.count)return;NSDictionary *f=fs[(NSUInteger)idx];[NSNotificationCenter.defaultCenter postNotificationName:ZNFeatureActionRequestedNotification object:self userInfo:ZN65EventInfo(f,nil,nil)];}
- (void)zn65fc_sliderCommitted:(ZNRangeControl*)slider{NSInteger idx=slider.tag-kZN65SliderTagBase;NSArray *fs=ZN65FeatureGroups();if(idx<0||(NSUInteger)idx>=fs.count)return;NSDictionary *f=fs[(NSUInteger)idx];double v=MAX(1.0,MIN(10.0,round(slider.value)));slider.value=v;NSString *text=[NSString stringWithFormat:@"%.0f",v];[NSUserDefaults.standardUserDefaults setDouble:v forKey:ZN65PreferenceKey(f,@"value")];[NSUserDefaults.standardUserDefaults setObject:text forKey:ZN65PreferenceKey(f,@"valueText")];[NSNotificationCenter.defaultCenter postNotificationName:ZNFeatureSliderValueDidChangeNotification object:self userInfo:ZN65EventInfo(f,@(v),text)];}
@end
extern "C" void ZNInstallFeatureRuntimeControlsV2Deferred(void){static dispatch_once_t once;dispatch_once(&once,^{Class cls=NSClassFromString(@"ZNRuntimeMenuControllerV040");if(!cls)return;Method a=class_getInstanceMethod(cls,@selector(zn50_renderFeatureGroupsFull)),b=class_getInstanceMethod(cls,@selector(zn65fc_renderFull));if(a&&b)method_exchangeImplementations(a,b);Method c=class_getInstanceMethod(cls,@selector(zn50_renderFeatureGroupsCompact)),d=class_getInstanceMethod(cls,@selector(zn65fc_renderCompact));if(c&&d)method_exchangeImplementations(c,d);[[ZNRuntimeLogger sharedLogger]log:@"[m5.12-offset] generated client ordinary controls installed"];});}
