#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <objc/runtime.h>
#include <math.h>

#import "ZNBinaryPatchWorkspace.h"
#import "ZNFeatureControlModel.h"
#import "ZNRuntimeActionModel.h"
#import "ZNTheme.h"
#import "ZNPatchCore.h"

// M6.4.1 canonical authoring renderer.
// One Builder surface. Backend and Control are orthogonal data choices.
// Runtime Method and Static Patch are rendered by this same card renderer.

static NSString * const kM641BackendPrefix = @"zonoe.m6.4.1.backend.v1";
static NSString * const kM641ControlPrefix = @"zonoe.m6.4.1.control.v1";
static NSString * const kM641SliderPrefix  = @"zonoe.m5.8.5.static-slider-max.v1";
static NSString * const kM641ValuePrefix   = @"zonoe.m6.4.offset-fixed-value.v1";
static const NSInteger kM641Target       = 440000;
static const NSInteger kM641OffsetField  = 441000;
static const NSInteger kM641Name         = 710000;
static const NSInteger kM641Desc         = 711000;
static const NSInteger kM641Backend      = 712000;
static const NSInteger kM641Control      = 713000;
static const NSInteger kM641Aux          = 714000;
static const NSInteger kM641Delete       = 715000;
static const NSInteger kM641RuntimeName  = 720000;
static const NSInteger kM641RuntimeDesc  = 721000;
static const NSInteger kM641RuntimeCtl   = 722000;
static const NSInteger kM641RuntimeAux   = 723000;
static const NSInteger kM641RuntimeDel   = 724000;

typedef NS_ENUM(NSInteger,M641Backend){M641BackendRuntime=0,M641BackendStatic=1};
typedef NS_ENUM(NSInteger,M641StaticControl){M641StaticHex=0,M641StaticSwitch=1,M641StaticNumber=2,M641StaticSlider=3,M641StaticButton=4};

@interface ZNRuntimeMenuControllerV040 : NSObject
@property(nonatomic,strong) UIView *contentView;
@property(nonatomic,strong) UIWindow *hostWindow;
@property(nonatomic,strong) ZNTheme *theme;
- (UIView *)cardAtY:(CGFloat)y height:(CGFloat)h width:(CGFloat)w compact:(BOOL)compact;
- (UILabel *)label:(NSString *)text size:(CGFloat)size weight:(UIFontWeight)weight color:(UIColor *)color;
- (UIButton *)zn40_button:(NSString *)title selector:(SEL)selector frame:(CGRect)frame;
- (UITextField *)zn44_field:(CGRect)frame text:(NSString *)text placeholder:(NSString *)placeholder tag:(NSInteger)tag enabled:(BOOL)enabled;
- (void)zn40_updateContentHeight:(CGFloat)y;
- (void)renderPage;
- (void)zn44_renderOther;
- (void)zn44_buildBinary:(id)sender;
@end

static NSString *M641Trim(NSString *s){return [(s?:@"") stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];}
static NSString *M641NameForRow(ZNBinaryPatchRow *r){NSString *g=M641Trim(r.group);if(g.length&&[g caseInsensitiveCompare:@"Imported"]!=NSOrderedSame)return g;NSString *t=M641Trim(r.title);return t.length?t:@"未命名功能";}
static NSString *M641Key(NSString *prefix,NSString *name){return [NSString stringWithFormat:@"%@.%@",prefix,M641Trim(name).lowercaseString];}
static BOOL M641Placeholder(ZNBinaryPatchRow *r){NSString *g=M641Trim(r.group),*t=M641Trim(r.title);BOOL pg=!g.length||[g caseInsensitiveCompare:@"Imported"]==NSOrderedSame;return !r.offsetText.length&&!r.enabledText.length&&!t.length&&pg;}
static NSArray<ZNBinaryPatchRow *> *M641Rows(void){ZNBinaryPatchWorkspace *w=[ZNBinaryPatchWorkspace sharedWorkspace];[w ensureDefaultRows];NSMutableArray *out=[NSMutableArray array];for(ZNBinaryPatchRow *r in w.rows){if(M641Placeholder(r))continue;NSString *name=M641NameForRow(r);BOOL dup=NO;for(ZNBinaryPatchRow *x in out)if([M641NameForRow(x) caseInsensitiveCompare:name]==NSOrderedSame){dup=YES;break;}if(!dup)[out addObject:r];}return [out copy];}

static M641Backend M641BackendForRow(ZNBinaryPatchRow *r){NSString *s=[NSUserDefaults.standardUserDefaults stringForKey:M641Key(kM641BackendPrefix,M641NameForRow(r))];if([s isEqualToString:@"static"])return M641BackendStatic;if([s isEqualToString:@"runtime"])return M641BackendRuntime;return r.enabledText.length?M641BackendStatic:M641BackendRuntime;}
static void M641SetBackend(ZNBinaryPatchRow *r,M641Backend b){[NSUserDefaults.standardUserDefaults setObject:(b==M641BackendStatic?@"static":@"runtime") forKey:M641Key(kM641BackendPrefix,M641NameForRow(r))];}
static M641StaticControl M641StaticControlForRow(ZNBinaryPatchRow *r){NSString *s=[NSUserDefaults.standardUserDefaults stringForKey:M641Key(kM641ControlPrefix,M641NameForRow(r))];if([s isEqualToString:@"switch"])return M641StaticSwitch;if([s isEqualToString:@"number"])return M641StaticNumber;if([s isEqualToString:@"slider"])return M641StaticSlider;if([s isEqualToString:@"button"])return M641StaticButton;return M641StaticHex;}
static NSString *M641StaticControlName(M641StaticControl c){switch(c){case M641StaticSwitch:return @"开关";case M641StaticNumber:return @"数值";case M641StaticSlider:return @"滑块";case M641StaticButton:return @"按钮";default:return @"HEX";}}
static NSString *M641StaticControlDisplay(M641StaticControl c){switch(c){case M641StaticSwitch:return @"开关 Patch";case M641StaticNumber:return @"数值输入";case M641StaticSlider:return @"滑块";case M641StaticButton:return @"按钮 Patch";default:return @"16进制 Patch";}}
static NSString *M641RuntimeControlDisplay(ZNRuntimeArgumentControlType c){switch(c){case ZNRuntimeArgumentControlTypeFixed:return @"固定值";case ZNRuntimeArgumentControlTypeNumber:return @"数值输入";case ZNRuntimeArgumentControlTypeSlider:return @"滑块";case ZNRuntimeArgumentControlTypeSwitch:return @"开关";case ZNRuntimeArgumentControlTypeButton:return @"按钮";default:return ZNRuntimeArgumentControlTypeName(c);}}
static NSString *M641Purpose(BOOL runtime,ZNRuntimeArgumentControlType rc,M641StaticControl sc){if(runtime){switch(rc){case ZNRuntimeArgumentControlTypeFixed:return @"用途：Offset 定位 IL2CPP 方法，使用固定参数调用";case ZNRuntimeArgumentControlTypeNumber:return @"用途：客户输入数值后调用 Offset 对应的 IL2CPP 方法";case ZNRuntimeArgumentControlTypeSlider:return @"用途：客户拖动滑块后调用 Offset 对应的 IL2CPP 方法";case ZNRuntimeArgumentControlTypeSwitch:return @"用途：客户开关改变参数并调用 IL2CPP 方法";case ZNRuntimeArgumentControlTypeButton:return @"用途：客户点击按钮后调用 IL2CPP 方法";default:return @"用途：Offset → IL2CPP Runtime Method";}}switch(sc){case M641StaticHex:return @"用途：把 16 进制 Patch 直接写入 Offset";case M641StaticSwitch:return @"用途：客户开关启用 / 恢复这个 Patch";case M641StaticNumber:return @"用途：客户输入数值 → Static Value Cell";case M641StaticSlider:return @"用途：客户拖动滑块 → Static Value Cell";case M641StaticButton:return @"用途：客户点击按钮时应用 Patch";default:return @"用途：Offset → Static Patch";}}
static UIColor *M641StatusColor(NSString *status,ZNTheme *theme){NSString *s=M641Trim(status);if([s hasPrefix:@"❌"])return UIColor.systemRedColor;if([s hasPrefix:@"✅"])return UIColor.systemGreenColor;if([s hasPrefix:@"⚠"])return UIColor.systemOrangeColor;return theme.secondaryTextColor;}
static void M641SetStaticControl(ZNBinaryPatchRow *r,M641StaticControl c){NSString *s=@"hex";switch(c){case M641StaticSwitch:s=@"switch";break;case M641StaticNumber:s=@"number";break;case M641StaticSlider:s=@"slider";break;case M641StaticButton:s=@"button";break;default:break;}[NSUserDefaults.standardUserDefaults setObject:s forKey:M641Key(kM641ControlPrefix,M641NameForRow(r))];if(c==M641StaticNumber)r.featureControlType=ZNFeatureControlTypeNumber;else if(c==M641StaticSlider)r.featureControlType=ZNFeatureControlTypeSlider;else if(c==M641StaticButton)r.featureControlType=ZNFeatureControlTypeButton;else r.featureControlType=ZNFeatureControlTypeSwitch;}
static ZNRuntimeArgumentControlType M641RuntimeControl(ZNBinaryPatchRow *r){NSString *s=[NSUserDefaults.standardUserDefaults stringForKey:M641Key(kM641ControlPrefix,M641NameForRow(r))];if(s.length)return ZNRuntimeArgumentControlTypeFromKey(s);switch(r.featureControlType){case ZNFeatureControlTypeSlider:return ZNRuntimeArgumentControlTypeSlider;case ZNFeatureControlTypeSwitch:return ZNRuntimeArgumentControlTypeSwitch;case ZNFeatureControlTypeButton:return ZNRuntimeArgumentControlTypeButton;default:return ZNRuntimeArgumentControlTypeNumber;}}
static void M641SetRuntimeControl(ZNBinaryPatchRow *r,ZNRuntimeArgumentControlType c){[NSUserDefaults.standardUserDefaults setObject:ZNRuntimeArgumentControlTypeKey(c) forKey:M641Key(kM641ControlPrefix,M641NameForRow(r))];r.featureControlType=(c==ZNRuntimeArgumentControlTypeSlider)?ZNFeatureControlTypeSlider:(c==ZNRuntimeArgumentControlTypeSwitch?ZNFeatureControlTypeSwitch:(c==ZNRuntimeArgumentControlTypeButton?ZNFeatureControlTypeButton:ZNFeatureControlTypeNumber));}
static ZNRuntimeArgumentControlType M641NextRuntime(ZNRuntimeArgumentControlType c){switch(c){case ZNRuntimeArgumentControlTypeFixed:return ZNRuntimeArgumentControlTypeNumber;case ZNRuntimeArgumentControlTypeNumber:return ZNRuntimeArgumentControlTypeSlider;case ZNRuntimeArgumentControlTypeSlider:return ZNRuntimeArgumentControlTypeSwitch;case ZNRuntimeArgumentControlTypeSwitch:return ZNRuntimeArgumentControlTypeButton;default:return ZNRuntimeArgumentControlTypeFixed;}}
static M641StaticControl M641NextStatic(M641StaticControl c){return (M641StaticControl)(((NSInteger)c+1)%5);}
static ZNRuntimeArgumentControlType M641ActionControl(ZNRuntimeMethodAction *a){if(a.argumentCount!=1||a.argumentControlConfigs.count!=1)return ZNRuntimeArgumentControlTypeFixed;NSDictionary *cfg=a.argumentControlConfigs.firstObject;return [cfg[@"enabled"]boolValue]?ZNRuntimeArgumentControlTypeFromKey(cfg[@"type"]):ZNRuntimeArgumentControlTypeFixed;}
static UITextField *M641Field(CGRect f,ZNTheme *t){UITextField *x=[[UITextField alloc]initWithFrame:f];x.textColor=t.primaryTextColor;x.backgroundColor=t.controlColor;x.font=[UIFont systemFontOfSize:10 weight:UIFontWeightMedium];x.autocorrectionType=UITextAutocorrectionTypeNo;x.autocapitalizationType=UITextAutocapitalizationTypeNone;x.returnKeyType=UIReturnKeyDone;x.clearButtonMode=UITextFieldViewModeWhileEditing;x.layer.cornerRadius=7;x.layer.borderWidth=1;x.layer.borderColor=t.borderColor.CGColor;UIView *p=[[UIView alloc]initWithFrame:CGRectMake(0,0,8,1)];x.leftView=p;x.leftViewMode=UITextFieldViewModeAlways;return x;}
static void M641Persist(void){ZNBinaryPatchWorkspace *w=[ZNBinaryPatchWorkspace sharedWorkspace];[w updateDefaultTarget:w.defaultTarget];}
static BOOL M641ValidateStaticRows(ZNBinaryPatchWorkspace *w,NSString **error){NSArray<ZNBinaryPatchRow *> *original=[w.rows copy];NSMutableArray<ZNBinaryPatchRow *> *staticRows=[NSMutableArray array];for(ZNBinaryPatchRow *r in original){if(M641Placeholder(r))continue;if(M641BackendForRow(r)==M641BackendStatic)[staticRows addObject:r];}if(!staticRows.count)return YES;[w.rows removeAllObjects];[w.rows addObjectsFromArray:staticRows];NSString *e=nil;BOOL ok=[w validateAll:&e];[w.rows removeAllObjects];[w.rows addObjectsFromArray:original];if(!ok&&error)*error=e?:@"Static Patch 验证失败";return ok;}

@interface ZNRuntimeMenuControllerV040 (M641Authoring)
- (void)m641_renderOther;- (void)m641_target:(UITextField *)f;- (void)m641_add:(id)s;- (void)m641_name:(UITextField *)f;- (void)m641_desc:(UITextField *)f;- (void)m641_backend:(UIButton *)b;- (void)m641_control:(UIButton *)b;- (void)m641_aux:(UITextField *)f;- (void)m641_delete:(UIButton *)b;- (void)m641_runtimeName:(UITextField *)f;- (void)m641_runtimeDesc:(UITextField *)f;- (void)m641_runtimeCtl:(UIButton *)b;- (void)m641_runtimeAux:(UITextField *)f;- (void)m641_runtimeDel:(UIButton *)b;- (void)m641_build:(id)s;
@end

@implementation ZNRuntimeMenuControllerV040 (M641Authoring)
- (void)m641_renderOther{
    [self.contentView.subviews makeObjectsPerformSelector:@selector(removeFromSuperview)];CGFloat width=CGRectGetWidth(self.contentView.bounds),y=9;ZNBinaryPatchWorkspace *w=[ZNBinaryPatchWorkspace sharedWorkspace];BOOL locked=w.isBuilding||w.hasAnyApplied;
    UIView *tc=[self cardAtY:y height:56 width:width compact:NO];UILabel *bl=[self label:@"二进制" size:10.2 weight:UIFontWeightSemibold color:self.theme.primaryTextColor];bl.frame=CGRectMake(13,11,48,32);[tc addSubview:bl];UITextField *tf=M641Field(CGRectMake(65,11,tc.bounds.size.width-78,32),self.theme);tf.tag=kM641Target;tf.text=w.defaultTarget;tf.placeholder=@"UnityFramework / 主程序 / 其他 dylib";tf.enabled=!locked;[tf addTarget:self action:@selector(m641_target:) forControlEvents:UIControlEventEditingDidEnd|UIControlEventEditingDidEndOnExit];[tc addSubview:tf];[self.contentView addSubview:tc];y+=64;
    UIView *intro=[self cardAtY:y height:58 width:width compact:NO];UILabel *a=[self label:@"功能制作 · 执行方式与客户控件" size:9.6 weight:UIFontWeightSemibold color:self.theme.primaryTextColor];a.frame=CGRectMake(13,7,intro.bounds.size.width-26,19);[intro addSubview:a];UILabel *b=[self label:@"左侧选怎么执行；右侧选客户菜单显示什么控件（点按切换）" size:8.2 weight:UIFontWeightRegular color:self.theme.secondaryTextColor];b.frame=CGRectMake(13,29,intro.bounds.size.width-26,20);b.numberOfLines=2;[intro addSubview:b];[self.contentView addSubview:intro];y+=66;
    NSArray *rows=M641Rows();
    for(NSUInteger i=0;i<rows.count;i++){
        ZNBinaryPatchRow *r=rows[i];NSString *name=M641NameForRow(r);M641Backend backend=M641BackendForRow(r);ZNRuntimeArgumentControlType rc=M641RuntimeControl(r);M641StaticControl sc=M641StaticControlForRow(r);BOOL runtime=backend==M641BackendRuntime;BOOL aux=runtime?(rc==ZNRuntimeArgumentControlTypeSlider||rc==ZNRuntimeArgumentControlTypeFixed||rc==ZNRuntimeArgumentControlTypeButton):(sc==M641StaticHex||sc==M641StaticSwitch||sc==M641StaticButton||sc==M641StaticSlider);BOOL hasStatus=M641Trim(r.statusText).length>0;CGFloat h=(aux?216:181)+(hasStatus?29:0);UIView *c=[self cardAtY:y height:h width:width compact:NO];CGFloat x=13,fw=c.bounds.size.width-71;
        UILabel *l1=[self label:@"功能名" size:8.6 weight:UIFontWeightMedium color:self.theme.secondaryTextColor];l1.frame=CGRectMake(x,7,42,29);[c addSubview:l1];UITextField *nf=M641Field(CGRectMake(58,7,fw,29),self.theme);nf.tag=kM641Name+(NSInteger)i;nf.text=name;nf.enabled=!locked;[nf addTarget:self action:@selector(m641_name:) forControlEvents:UIControlEventEditingDidEnd|UIControlEventEditingDidEndOnExit];[c addSubview:nf];
        UILabel *l2=[self label:@"说明" size:8.6 weight:UIFontWeightMedium color:self.theme.secondaryTextColor];l2.frame=CGRectMake(x,42,42,29);[c addSubview:l2];UITextField *df=M641Field(CGRectMake(58,42,fw,29),self.theme);df.tag=kM641Desc+(NSInteger)i;df.text=([M641Trim(r.group) caseInsensitiveCompare:@"Imported"]==NSOrderedSame)?@"":M641Trim(r.title);df.placeholder=@"显示给客户的说明";df.enabled=!locked;[df addTarget:self action:@selector(m641_desc:) forControlEvents:UIControlEventEditingDidEnd|UIControlEventEditingDidEndOnExit];[c addSubview:df];
        UILabel *l3=[self label:@"Offset" size:8.6 weight:UIFontWeightMedium color:self.theme.secondaryTextColor];l3.frame=CGRectMake(x,77,42,29);[c addSubview:l3];NSUInteger gi=[w.rows indexOfObjectIdenticalTo:r];UITextField *off=[self zn44_field:CGRectMake(58,77,fw,29) text:r.offsetText placeholder:@"0x123456" tag:kM641OffsetField+(NSInteger)gi enabled:!locked];[c addSubview:off];
        UIButton *bb=[self zn40_button:[NSString stringWithFormat:@"执行方式 · %@",runtime?@"Runtime（IL2CPP）":@"Static Patch"] selector:@selector(m641_backend:) frame:CGRectMake(x,112,(c.bounds.size.width-31)*.52,29)];bb.tag=kM641Backend+(NSInteger)i;bb.enabled=!locked;[c addSubview:bb];UIButton *cb=[self zn40_button:[NSString stringWithFormat:@"客户控件 · %@",runtime?M641RuntimeControlDisplay(rc):M641StaticControlDisplay(sc)] selector:@selector(m641_control:) frame:CGRectMake(CGRectGetMaxX(bb.frame)+5,112,c.bounds.size.width-CGRectGetMaxX(bb.frame)-18,29)];cb.tag=kM641Control+(NSInteger)i;cb.enabled=!locked;[c addSubview:cb];
        UIButton *del=[self zn40_button:@"删除" selector:@selector(m641_delete:) frame:CGRectMake(c.bounds.size.width-62,147,49,29)];del.tag=kM641Delete+(NSInteger)i;del.enabled=!locked;[c addSubview:del];UILabel *mode=[self label:M641Purpose(runtime,rc,sc) size:8.1 weight:UIFontWeightRegular color:self.theme.secondaryTextColor];mode.frame=CGRectMake(x,147,c.bounds.size.width-82,29);mode.adjustsFontSizeToFitWidth=YES;mode.minimumScaleFactor=.75;[c addSubview:mode];
        if(aux){UILabel *al=[self label:(runtime?(rc==ZNRuntimeArgumentControlTypeSlider?@"Max":@"Value"):(sc==M641StaticSlider?@"Max":@"Patch HEX")) size:8.6 weight:UIFontWeightMedium color:self.theme.secondaryTextColor];al.frame=CGRectMake(x,182,52,29);[c addSubview:al];UITextField *af=M641Field(CGRectMake(67,182,c.bounds.size.width-80,29),self.theme);af.tag=kM641Aux+(NSInteger)i;af.enabled=!locked;af.keyboardType=(runtime||sc==M641StaticSlider)?UIKeyboardTypeNumbersAndPunctuation:UIKeyboardTypeASCIICapable;if(runtime){if(rc==ZNRuntimeArgumentControlTypeSlider){id m=[NSUserDefaults.standardUserDefaults objectForKey:M641Key(kM641SliderPrefix,name)];af.text=[m isKindOfClass:NSNumber.class]?[(NSNumber *)m stringValue]:@"";af.placeholder=@"例如 31";}else{af.text=[NSUserDefaults.standardUserDefaults stringForKey:M641Key(kM641ValuePrefix,name)]?:@"";af.placeholder=@"例如 10000";}}else if(sc==M641StaticSlider){id m=[NSUserDefaults.standardUserDefaults objectForKey:M641Key(kM641SliderPrefix,name)];af.text=[m isKindOfClass:NSNumber.class]?[(NSNumber *)m stringValue]:@"";af.placeholder=@"例如 31";}else{af.text=r.enabledText;af.placeholder=@"例如 1F2003D5 / C0035FD6";}[af addTarget:self action:@selector(m641_aux:) forControlEvents:UIControlEventEditingChanged|UIControlEventEditingDidEnd|UIControlEventEditingDidEndOnExit];[c addSubview:af];}
        if(hasStatus){CGFloat sy=aux?216:181;UILabel *st=[self label:r.statusText size:8.4 weight:UIFontWeightSemibold color:M641StatusColor(r.statusText,self.theme)];st.frame=CGRectMake(x,sy,c.bounds.size.width-26,24);st.numberOfLines=2;st.lineBreakMode=NSLineBreakByTruncatingTail;[c addSubview:st];}
        [self.contentView addSubview:c];y+=h+8;
    }
    UIView *add=[self cardAtY:y height:46 width:width compact:NO];UIButton *ab=[self zn40_button:@"＋ 增加功能" selector:@selector(m641_add:) frame:CGRectMake(13,7,add.bounds.size.width-26,32)];ab.enabled=!locked;[add addSubview:ab];[self.contentView addSubview:add];y+=54;
    NSArray *actions=[[ZNRuntimeActionStore sharedStore]actionsSnapshot];UIView *rh=[self cardAtY:y height:40 width:width compact:NO];UILabel *rhl=[self label:[NSString stringWithFormat:@"Runtime Method · %lu",(unsigned long)actions.count] size:10.2 weight:UIFontWeightSemibold color:self.theme.primaryTextColor];rhl.frame=CGRectMake(13,6,rh.bounds.size.width-26,28);[rh addSubview:rhl];[self.contentView addSubview:rh];y+=48;
    for(NSUInteger i=0;i<actions.count;i++){ZNRuntimeMethodAction *act=actions[i];BOOL one=act.argumentCount==1;ZNRuntimeArgumentControlType ct=M641ActionControl(act);CGFloat h=one?151:112;UIView *c=[self cardAtY:y height:h width:width compact:NO];UITextField *nf=M641Field(CGRectMake(13,7,c.bounds.size.width-76,29),self.theme);nf.tag=kM641RuntimeName+(NSInteger)i;nf.text=act.title;nf.placeholder=act.methodName;[nf addTarget:self action:@selector(m641_runtimeName:) forControlEvents:UIControlEventEditingDidEnd|UIControlEventEditingDidEndOnExit];[c addSubview:nf];UIButton *del=[self zn40_button:@"删除" selector:@selector(m641_runtimeDel:) frame:CGRectMake(c.bounds.size.width-58,7,45,29)];del.tag=kM641RuntimeDel+(NSInteger)i;[c addSubview:del];UITextField *df=M641Field(CGRectMake(13,42,c.bounds.size.width-26,29),self.theme);df.tag=kM641RuntimeDesc+(NSInteger)i;df.text=([act.group caseInsensitiveCompare:@"Runtime Methods"]==NSOrderedSame)?@"":act.group;df.placeholder=@"说明（显示给客户）";[df addTarget:self action:@selector(m641_runtimeDesc:) forControlEvents:UIControlEventEditingDidEnd|UIControlEventEditingDidEndOnExit];[c addSubview:df];UILabel *idn=[self label:act.canonicalIdentity size:7.4 weight:UIFontWeightRegular color:self.theme.secondaryTextColor];idn.frame=CGRectMake(13,77,c.bounds.size.width-26,25);idn.numberOfLines=2;[c addSubview:idn];if(one){UIButton *ctl=[self zn40_button:[NSString stringWithFormat:@"客户控件 · %@",M641RuntimeControlDisplay(ct)] selector:@selector(m641_runtimeCtl:) frame:CGRectMake(13,111,c.bounds.size.width*.5-17,31)];ctl.tag=kM641RuntimeCtl+(NSInteger)i;[c addSubview:ctl];if(ct==ZNRuntimeArgumentControlTypeSlider||ct==ZNRuntimeArgumentControlTypeFixed||ct==ZNRuntimeArgumentControlTypeButton){UITextField *af=M641Field(CGRectMake(c.bounds.size.width*.5+2,111,c.bounds.size.width*.5-15,31),self.theme);af.tag=kM641RuntimeAux+(NSInteger)i;af.keyboardType=UIKeyboardTypeNumbersAndPunctuation;if(ct==ZNRuntimeArgumentControlTypeSlider){NSDictionary *cfg=act.argumentControlConfigs.firstObject;af.text=[cfg[@"max"]description];af.placeholder=@"Max";}else{af.text=act.argumentValues.firstObject?:@"";af.placeholder=@"Value";}[af addTarget:self action:@selector(m641_runtimeAux:) forControlEvents:UIControlEventEditingChanged|UIControlEventEditingDidEnd];[c addSubview:af];}}[self.contentView addSubview:c];y+=h+8;}
    UIView *bc=[self cardAtY:y height:52 width:width compact:NO];UIButton *build=[self zn40_button:(w.isBuilding?@"正在生成…":@"解析并生成新二进制") selector:@selector(m641_build:) frame:CGRectMake(13,9,bc.bounds.size.width-26,34)];build.enabled=!w.isBuilding&&!w.hasAnyApplied&&(rows.count||actions.count);[bc addSubview:build];[self.contentView addSubview:bc];y+=60;if(w.lastStatus.length){UIView *scard=[self cardAtY:y height:46 width:width compact:NO];UIColor *globalColor=[w.lastStatus containsString:@"失败"]?UIColor.systemRedColor:self.theme.secondaryTextColor;UILabel *sl=[self label:w.lastStatus size:8.2 weight:UIFontWeightRegular color:globalColor];sl.frame=CGRectMake(13,6,scard.bounds.size.width-26,34);sl.numberOfLines=2;[scard addSubview:sl];[self.contentView addSubview:scard];y+=54;}[self zn40_updateContentHeight:y];
}

- (void)m641_target:(UITextField *)f{ZNBinaryPatchWorkspace *w=[ZNBinaryPatchWorkspace sharedWorkspace];NSString *t=M641Trim(f.text);if(!t.length)t=@"UnityFramework";[w updateDefaultTarget:t];for(ZNBinaryPatchRow *r in w.rows){if(!M641Placeholder(r)){r.target=t;r.explicitTarget=YES;r.validated=NO;r.validator=nil;r.statusText=@"";}}f.text=w.defaultTarget;[f resignFirstResponder];}
- (void)m641_add:(id)s{(void)s;ZNBinaryPatchWorkspace *w=[ZNBinaryPatchWorkspace sharedWorkspace];if(w.isBuilding||w.hasAnyApplied)return;NSUInteger n=1;NSMutableSet *used=[NSMutableSet set];for(ZNBinaryPatchRow *r in M641Rows())[used addObject:M641NameForRow(r).lowercaseString];NSString *name=nil;do{name=[NSString stringWithFormat:@"新功能 %lu",(unsigned long)n++];}while([used containsObject:name.lowercaseString]);ZNBinaryPatchRow *r=[ZNBinaryPatchRow new];r.group=name;r.title=@"";r.target=w.defaultTarget;r.explicitTarget=YES;r.statusText=@"⚠ 待填写 Offset";r.featureControlType=ZNFeatureControlTypeNumber;[w.rows addObject:r];M641SetBackend(r,M641BackendRuntime);M641SetRuntimeControl(r,ZNRuntimeArgumentControlTypeNumber);M641Persist();[self renderPage];}
- (void)m641_name:(UITextField *)f{NSInteger i=f.tag-kM641Name;NSArray *rows=M641Rows();if(i<0||(NSUInteger)i>=rows.count)return;ZNBinaryPatchRow *r=rows[(NSUInteger)i];NSString *old=M641NameForRow(r),*name=M641Trim(f.text);if(!name.length){f.text=old;return;}for(NSString *p in @[kM641BackendPrefix,kM641ControlPrefix,kM641SliderPrefix,kM641ValuePrefix]){NSString *ok=M641Key(p,old),*nk=M641Key(p,name);id v=[NSUserDefaults.standardUserDefaults objectForKey:ok];if(v){[NSUserDefaults.standardUserDefaults setObject:v forKey:nk];[NSUserDefaults.standardUserDefaults removeObjectForKey:ok];}}r.group=name;M641Persist();[f resignFirstResponder];}
- (void)m641_desc:(UITextField *)f{NSInteger i=f.tag-kM641Desc;NSArray<ZNBinaryPatchRow *> *rows=M641Rows();if(i<0||(NSUInteger)i>=rows.count)return;ZNBinaryPatchRow *r=rows[(NSUInteger)i];r.title=M641Trim(f.text);M641Persist();[f resignFirstResponder];}
- (void)m641_backend:(UIButton *)b{NSInteger i=b.tag-kM641Backend;NSArray *rows=M641Rows();if(i<0||(NSUInteger)i>=rows.count)return;ZNBinaryPatchRow *r=rows[(NSUInteger)i];M641Backend n=M641BackendForRow(r)==M641BackendRuntime?M641BackendStatic:M641BackendRuntime;M641SetBackend(r,n);if(n==M641BackendStatic){M641SetStaticControl(r,M641StaticHex);}else{r.enabledText=@"";M641SetRuntimeControl(r,ZNRuntimeArgumentControlTypeNumber);}r.validated=NO;r.validator=nil;r.statusText=@"";M641Persist();[self renderPage];}
- (void)m641_control:(UIButton *)b{NSInteger i=b.tag-kM641Control;NSArray *rows=M641Rows();if(i<0||(NSUInteger)i>=rows.count)return;ZNBinaryPatchRow *r=rows[(NSUInteger)i];if(M641BackendForRow(r)==M641BackendRuntime){M641SetRuntimeControl(r,M641NextRuntime(M641RuntimeControl(r)));r.enabledText=@"";}else{M641StaticControl n=M641NextStatic(M641StaticControlForRow(r));M641SetStaticControl(r,n);if(n==M641StaticNumber||n==M641StaticSlider)r.enabledText=@"";}r.validated=NO;r.validator=nil;r.statusText=@"";M641Persist();[self renderPage];}
- (void)m641_aux:(UITextField *)f{NSInteger i=f.tag-kM641Aux;NSArray *rows=M641Rows();if(i<0||(NSUInteger)i>=rows.count)return;ZNBinaryPatchRow *r=rows[(NSUInteger)i];NSString *name=M641NameForRow(r);if(M641BackendForRow(r)==M641BackendRuntime){ZNRuntimeArgumentControlType c=M641RuntimeControl(r);if(c==ZNRuntimeArgumentControlTypeSlider){double m=f.text.doubleValue;NSString *k=M641Key(kM641SliderPrefix,name);if(isfinite(m)&&m>0)[NSUserDefaults.standardUserDefaults setDouble:m forKey:k];else[NSUserDefaults.standardUserDefaults removeObjectForKey:k];}else{NSString *k=M641Key(kM641ValuePrefix,name),*v=M641Trim(f.text);if(v.length)[NSUserDefaults.standardUserDefaults setObject:v forKey:k];else[NSUserDefaults.standardUserDefaults removeObjectForKey:k];}}else{M641StaticControl c=M641StaticControlForRow(r);if(c==M641StaticSlider){double m=f.text.doubleValue;NSString *k=M641Key(kM641SliderPrefix,name);if(isfinite(m)&&m>0)[NSUserDefaults.standardUserDefaults setDouble:m forKey:k];else[NSUserDefaults.standardUserDefaults removeObjectForKey:k];}else r.enabledText=[M641Trim(f.text) uppercaseString];}r.validated=NO;r.validator=nil;r.statusText=@"";}
- (void)m641_delete:(UIButton *)b{NSInteger i=b.tag-kM641Delete;NSArray *rows=M641Rows();if(i<0||(NSUInteger)i>=rows.count)return;ZNBinaryPatchWorkspace *w=[ZNBinaryPatchWorkspace sharedWorkspace];ZNBinaryPatchRow *v=rows[(NSUInteger)i];NSString *name=M641NameForRow(v);[w.rows removeObjectIdenticalTo:v];for(NSString *p in @[kM641BackendPrefix,kM641ControlPrefix,kM641SliderPrefix,kM641ValuePrefix])[NSUserDefaults.standardUserDefaults removeObjectForKey:M641Key(p,name)];[w ensureDefaultRows];M641Persist();[self renderPage];}
- (void)m641_runtimeName:(UITextField *)f{NSInteger i=f.tag-kM641RuntimeName;if(i>=0)[[ZNRuntimeActionStore sharedStore]updateTitle:f.text atIndex:(NSUInteger)i error:nil];[f resignFirstResponder];}
- (void)m641_runtimeDesc:(UITextField *)f{NSInteger i=f.tag-kM641RuntimeDesc;if(i>=0)[[ZNRuntimeActionStore sharedStore]updateGroup:f.text atIndex:(NSUInteger)i error:nil];[f resignFirstResponder];}
- (void)m641_runtimeCtl:(UIButton *)b{NSInteger i=b.tag-kM641RuntimeCtl;NSArray *a=[[ZNRuntimeActionStore sharedStore]actionsSnapshot];if(i<0||(NSUInteger)i>=a.count)return;ZNRuntimeMethodAction *x=a[(NSUInteger)i];if(x.argumentCount!=1)return;ZNRuntimeArgumentControlType n=M641NextRuntime(M641ActionControl(x));NSMutableDictionary *cfg=[x.argumentControlConfigs.firstObject mutableCopy]?:[NSMutableDictionary dictionary];cfg[@"enabled"]=@(n!=ZNRuntimeArgumentControlTypeFixed);cfg[@"type"]=ZNRuntimeArgumentControlTypeKey(n);if(n==ZNRuntimeArgumentControlTypeSlider){double m=[cfg[@"max"]doubleValue];if(!isfinite(m)||m<=0)m=10;cfg[@"min"]=@0;cfg[@"max"]=@(m);cfg[@"step"]=@1;cfg[@"default"]=@(m);}[[ZNRuntimeActionStore sharedStore]updateArgumentControlConfigs:@[[cfg copy]] atIndex:(NSUInteger)i error:nil];[self renderPage];}
- (void)m641_runtimeAux:(UITextField *)f{NSInteger i=f.tag-kM641RuntimeAux;NSArray *a=[[ZNRuntimeActionStore sharedStore]actionsSnapshot];if(i<0||(NSUInteger)i>=a.count)return;ZNRuntimeMethodAction *x=a[(NSUInteger)i];if(x.argumentCount!=1)return;ZNRuntimeArgumentControlType c=M641ActionControl(x);if(c==ZNRuntimeArgumentControlTypeSlider){double m=f.text.doubleValue;if(!isfinite(m)||m<=0)return;NSMutableDictionary *cfg=[x.argumentControlConfigs.firstObject mutableCopy]?:[NSMutableDictionary dictionary];cfg[@"enabled"]=@YES;cfg[@"type"]=ZNRuntimeArgumentControlTypeKey(c);cfg[@"min"]=@0;cfg[@"max"]=@(m);cfg[@"step"]=@1;cfg[@"default"]=@(m);[[ZNRuntimeActionStore sharedStore]updateArgumentControlConfigs:@[[cfg copy]] atIndex:(NSUInteger)i error:nil];[[ZNRuntimeActionStore sharedStore]updateArgumentValues:@[[NSString stringWithFormat:@"%.15g",m]] atIndex:(NSUInteger)i error:nil];}else if(c==ZNRuntimeArgumentControlTypeFixed||c==ZNRuntimeArgumentControlTypeButton){[[ZNRuntimeActionStore sharedStore]updateArgumentValues:@[M641Trim(f.text)] atIndex:(NSUInteger)i error:nil];}}
- (void)m641_runtimeDel:(UIButton *)b{NSInteger i=b.tag-kM641RuntimeDel;if(i>=0)[[ZNRuntimeActionStore sharedStore]removeActionAtIndex:(NSUInteger)i];[self renderPage];}
- (void)m641_build:(id)s{
    ZNBinaryPatchWorkspace *w=[ZNBinaryPatchWorkspace sharedWorkspace];NSArray<ZNBinaryPatchRow *> *rows=M641Rows();
    for(ZNBinaryPatchRow *r in rows){NSString *name=M641NameForRow(r);r.statusText=@"";if(!r.offsetText.length){r.statusText=@"❌ 必须填写 Offset";w.lastStatus=[NSString stringWithFormat:@"解析准备失败 · %@：必须填写 Offset",name];[self renderPage];return;}if(M641BackendForRow(r)==M641BackendRuntime){ZNRuntimeArgumentControlType c=M641RuntimeControl(r);if(c==ZNRuntimeArgumentControlTypeSlider){id m=[NSUserDefaults.standardUserDefaults objectForKey:M641Key(kM641SliderPrefix,name)];if(![m isKindOfClass:NSNumber.class]||[(NSNumber *)m doubleValue]<=0){r.statusText=@"❌ Runtime Slider Max 必须大于 0";w.lastStatus=[NSString stringWithFormat:@"解析准备失败 · %@：Slider Max 必须大于 0",name];[self renderPage];return;}}if((c==ZNRuntimeArgumentControlTypeFixed||c==ZNRuntimeArgumentControlTypeButton)&&![[NSUserDefaults.standardUserDefaults stringForKey:M641Key(kM641ValuePrefix,name)]length]){r.statusText=[NSString stringWithFormat:@"❌ %@ Value 不能为空",M641RuntimeControlDisplay(c)];w.lastStatus=[NSString stringWithFormat:@"解析准备失败 · %@：%@ Value 不能为空",name,M641RuntimeControlDisplay(c)];[self renderPage];return;}r.statusText=@"⚠ 待解析 IL2CPP exact Method";}else{M641StaticControl c=M641StaticControlForRow(r);if(c==M641StaticSlider){id m=[NSUserDefaults.standardUserDefaults objectForKey:M641Key(kM641SliderPrefix,name)];if(![m isKindOfClass:NSNumber.class]||[(NSNumber *)m doubleValue]<=0){r.statusText=@"❌ Static Slider Max 必须大于 0";w.lastStatus=[NSString stringWithFormat:@"解析准备失败 · %@：Static Slider Max 必须大于 0",name];[self renderPage];return;}}else if((c==M641StaticHex||c==M641StaticSwitch||c==M641StaticButton)&&!M641Trim(r.enabledText).length){r.statusText=@"❌ Patch HEX 不能为空";w.lastStatus=[NSString stringWithFormat:@"解析准备失败 · %@：Patch HEX 不能为空",name];[self renderPage];return;}}}
    NSString *e=nil;if(!M641ValidateStaticRows(w,&e)){ZNBinaryPatchRow *bad=nil;for(ZNBinaryPatchRow *r in rows){if(M641BackendForRow(r)==M641BackendStatic&&[M641Trim(r.statusText) hasPrefix:@"❌"]){bad=r;break;}}w.lastStatus=bad?[NSString stringWithFormat:@"解析准备失败 · %@：%@",M641NameForRow(bad),M641Trim(bad.statusText)]:[NSString stringWithFormat:@"解析准备失败：%@",e?:@"Static Patch 验证失败"];[self renderPage];return;}
    [self zn44_buildBinary:s];
}
@end

static void M641Swap(Class c,SEL a,SEL b){Method x=class_getInstanceMethod(c,a),y=class_getInstanceMethod(c,b);if(x&&y)method_exchangeImplementations(x,y);}
extern "C" void ZNInstallFeatureBuilderUIDeferred(void){static dispatch_once_t once;dispatch_once(&once,^{Class c=NSClassFromString(@"ZNRuntimeMenuControllerV040");if(!c)return;M641Swap(c,@selector(zn44_renderOther),@selector(m641_renderOther));[[ZNRuntimeLogger sharedLogger]log:@"[m6.4.1-authoring] one Builder renderer; explicit execution mode + customer control; per-feature status restored"];} );}
